Resources:
  UserMediaBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: ${self:service}-${sls:stage}
      AccelerateConfiguration:
        AccelerationStatus: Enabled
      WebsiteConfiguration:
        IndexDocument: default.png
        ErrorDocument: default.png
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000
  UserMediaDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          TargetOriginId: UserMediaBucket
          ViewerProtocolPolicy: allow-all
          Compress: true
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
        Enabled: true
        Origins:
          - Id: UserMediaBucket
            DomainName: ${self:service}-${sls:stage}.s3-website-${self:provider.region}.amazonaws.com
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
