service: trace-stack

plugins:
  - serverless-esbuild
  - serverless-offline
  # - serverless-domain-manager

params:
  default:
    DATA_RETENTION_DAYS: ${env:DATA_RETENTION_DAYS, 30}
    CUSTOM_DOMAIN: ${env:CUSTOM_DOMAIN, ""}

custom:
  # baseDomain: my-app.com
  # domain:
  #   production: api.${self:custom.baseDomain}
  #   default: api-${sls:stage}.${self:custom.baseDomain}
  # customDomain:
  #   domainName: ${self:custom.domain.${sls:stage}, self:custom.domain.default}
  #   stage: ${sls:stage}
  #   certificateName: ${self:custom.baseDomain}
  #   createRoute53Record: true
  #   endpointType: regional
  #   apiType: http
  #   autoDomain: true

package:
  individually: true

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 25
  region: eu-west-1
  deploymentMethod: direct
  versionFunctions: false
  stackTags:
    service: ${self:service}
  environment:
    SERVICE: ${self:service}
    # STAGE: ${sls:stage}
    DATA_RETENTION_DAYS: ${param:DATA_RETENTION_DAYS}
    NODE_ENV: ${sls:stage}
    TABLE_NAME: ${self:service}-${sls:stage}
    CUSTOM_DOMAIN: ${param:CUSTOM_DOMAIN}
    EDGE_ENDPOINT: !GetAtt HttpApi.ApiEndpoint
    # S3_BUCKET: ${self:service}-${sls:stage}
    # CLOUDFRONT_DOMAIN: !GetAtt UserMediaDistribution.DomainName
    # USER_POOL_ID:
    #   Ref: CognitoUserPool
  httpApi:
    payload: "2.0"
    cors: true
    # authorizers:
    #   WebAuthorizer:
    #     identitySource: $request.header.Authorization
    #     issuerUrl:
    #       Fn::Join:
    #         - ""
    #         - - "https://cognito-idp."
    #           - "${opt:region, self:provider.region}"
    #           - ".amazonaws.com/"
    #           - Ref: CognitoUserPool
    #     audience:
    #       Ref: CognitoUserPoolClient
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements: # TODO: define IAMs per function
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - "*"
        - Effect: Allow
          Action:
            - cognito-idp:*
          Resource:
            - "*"
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource:
            - "*"

layers:
  tracer:
    path: ../lambda-layer
    name: ${self:service}-layer
    description: Auto-tracing layer for your functions
    compatibleRuntimes:
      - nodejs16.x
      - nodejs18.x
      - nodejs20.x

functions:
  - ${file(./src/functions/hello-world/function.yml)}
  - ${file(./src/functions/collector/function.yml)}
#   - ${file(./src/functions/users/get/function.yml)}
#   - ${file(./src/functions/users/update/function.yml)}
#   - ${file(./src/functions/preferences/get/function.yml)}
#   - ${file(./src/functions/preferences/update/function.yml)}
#   - ${file(./src/functions/media/upload/function.yml)}

resources:
  - ${file(./src/infrastructure/database/table.yml)}
#   - ${file(./src/infrastructure/storage/bucket.yml)}
#   - ${file(./src/infrastructure/auth/auth-role.yml)}
#   - ${file(./src/infrastructure/auth/user-pool.yml)}
#   - ${file(./src/infrastructure/auth/identity-pool.yml)}
