name: E2E tests

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}

jobs:
  e2e:
    name: E2E tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::296062585054:role/github-actions-e2e
          aws-region: eu-west-1

      - name: Run e2e tests
        run: yarn turbo run test:e2e --output-logs=new-only --color --env-mode=loose
        env:
          AWS_REGION: eu-west-1
