name: Push

concurrency:
  group: push

on:
  push:
    branches:
      - main
    paths:
      - 'packages/deploy-script/**'
      - '.github/workflows/push.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build & test
        run: yarn build && yarn test

      - name: Install latest npm
        run: npm install -g npm@latest

      - name: Release deploy script
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
        run: yarn release
